/**@format */

const PROJECT_ERROR_CODE = {
    NO_PROJECT_NAME: 20000,
    NOT_SUPPORT_MACRO_DEF: 20001,
    NOT_SUPPORT_API: 20002,
    INVALID_OPERATION: 20003,

    NO_MATCHED_PARAMS: 20004,
};

module.exports.PROJECT_ERROR_CODE = PROJECT_ERROR_CODE;
